### ISSUE TITLE
Issue in including the passes

### ISSUE THREAD

**Issue by SCS89** [hal-lab-u-tokyo/CGRAOmp#1]
Kindly help me with this issue

![cgra_error](https://user-images.githubusercontent.com/41662618/192986551-bed8ae72-42c2-4450-b461-fab9d4dc9282.png)

**Comment by tkojima0107** [comment]
Thank you for reporting the issue. A quick solution is to set a environment variable "LD_LIBRARY_PATH". For example, executing the following command: `export LD_LIBRARY_PATH=`
I will update the compiler driver to handle this error .

**Comment by SCS89** [comment]
Thank you so much! Its working now.
